apiVersion: v1
kind: Secret
metadata:
  name: seekapa-secrets
  namespace: seekapa
  labels:
    app: seekapa
type: Opaque
stringData:
  # Database credentials
  postgres-user: "seekapa_admin"
  postgres-password: "S33kpDB2025"
  database-url: "postgresql://seekapa_admin:S33kpDB2025@seekapa-postgres-service:5432/seekapa_bi"

  # Redis credentials
  redis-password: "redis123"
  redis-url: "redis://seekapa-redis-service:6379"

  # Azure OpenAI API Key
  azure-openai-key: "7XVEqnMzQOOEALRYogvR5kuPj7v8r7wtJwZCzilq4u5KKh7DtTvNJQQJ99BFACfhMk5XJ3w3AAAAACOGmZgG"

  # Power BI credentials
  powerbi-tenant-id: "318030de-752f-42b3-9848-abd6ec3809e3"
  powerbi-client-id: "39e95282-848b-4d78-ba1a-f6a9c7dc1fc9"
  powerbi-client-secret: "zH48Q~ouOfJm3gRQC8Rgm0ZtzdQd3yGj5.yE.bzB"

  # JWT Secret
  jwt-secret: "seekapa-jwt-secret-2025-secure-key"

---
# Monitoring authentication secret
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-auth
  namespace: seekapa
  labels:
    app: seekapa-monitoring
type: Opaque
data:
  # htpasswd generated: admin:admin123
  auth: YWRtaW4kYXByMSRlU1dpZVZ1NkNuc0V3Lk9HOXJPU3Zma2c1azAyZTAwCgo=

---
# TLS Certificate Secret (managed by cert-manager)
apiVersion: v1
kind: Secret
metadata:
  name: seekapa-tls
  namespace: seekapa
  labels:
    app: seekapa
type: kubernetes.io/tls
data:
  # These will be automatically populated by cert-manager
  tls.crt: ""
  tls.key: ""

---
# Development TLS Certificate Secret
apiVersion: v1
kind: Secret
metadata:
  name: seekapa-dev-tls
  namespace: seekapa
  labels:
    app: seekapa
    env: development
type: kubernetes.io/tls
data:
  # These will be automatically populated by cert-manager
  tls.crt: ""
  tls.key: ""

---
# Monitoring TLS Certificate Secret
apiVersion: v1
kind: Secret
metadata:
  name: seekapa-monitoring-tls
  namespace: seekapa
  labels:
    app: seekapa-monitoring
type: kubernetes.io/tls
data:
  # These will be automatically populated by cert-manager
  tls.crt: ""
  tls.key: ""

---
# Docker registry secret for private images
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: seekapa
  labels:
    app: seekapa
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded Docker config JSON
  # Replace with actual registry credentials
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jb20iOnsidXNlcm5hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiJwYXNzIiwiYXV0aCI6ImRYTmxjanB3WVhOeiJ9fX0=