version: '3.8'

services:
  # Backend API Service (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: seekapa-backend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://seekapa_admin:S33kpDB2025@postgres:5432/seekapa_bi_dev
      - REDIS_URL=redis://redis:6379
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_AI_SERVICES_ENDPOINT=${AZURE_AI_SERVICES_ENDPOINT}
      - GPT5_DEPLOYMENT=${GPT5_DEPLOYMENT}
      - POWERBI_TENANT_ID=${POWERBI_TENANT_ID}
      - POWERBI_CLIENT_ID=${POWERBI_CLIENT_ID}
      - POWERBI_CLIENT_SECRET=${POWERBI_CLIENT_SECRET}
      - POWERBI_WORKSPACE_ID=${POWERBI_WORKSPACE_ID}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - UVICORN_RELOAD=true
      - LOG_LEVEL=debug
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - seekapa-dev-network

  # Frontend Service (Development with HMR)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: seekapa-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    networks:
      - seekapa-dev-network

  # PostgreSQL Database (Development)
  postgres:
    image: postgres:16-alpine
    container_name: seekapa-postgres-dev
    restart: unless-stopped
    environment:
      - POSTGRES_USER=seekapa_admin
      - POSTGRES_PASSWORD=S33kpDB2025
      - POSTGRES_DB=seekapa_bi_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./database/dev-seed.sql:/docker-entrypoint-initdb.d/dev-seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seekapa_admin -d seekapa_bi_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - seekapa-dev-network

  # Redis Cache Service (Development)
  redis:
    image: redis:7-alpine
    container_name: seekapa-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly no
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - seekapa-dev-network

  # Redis Commander (GUI for Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: seekapa-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - seekapa-dev-network

  # PgAdmin (GUI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: seekapa-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@seekapa.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "8082:80"
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - seekapa-dev-network

  # Mailhog (Email testing)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: seekapa-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - seekapa-dev-network

  # Development Tools Container
  devtools:
    build:
      context: ./devtools
      dockerfile: Dockerfile
    container_name: seekapa-devtools
    restart: unless-stopped
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    command: ["tail", "-f", "/dev/null"]
    networks:
      - seekapa-dev-network

networks:
  seekapa-dev-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  pgadmin_dev_data:
    driver: local